export const CHANGE_NAME = 'CHANGE_NAME';
export const CHANGE_USERNAME = 'CHANGE_USERNAME'
export const CHANGE_EMAIL = 'CHANGE_EMAIL'
export const CHANGE_WEBSITE = 'CHANGE_WEBSITE'
export const SET_ALL = 'SET_ALL'